// Network adapter. Each task calls one generation/edit endpoint; no automatic POST retry.
function findImagePayload(value,depth=0){if(!value||depth>8)return null;if(typeof value==="object"){if(value.b64_json||value.b64||value.partial_image_b64||value.image_url||value.url)return value;for(let child of Object.values(value)){let found=findImagePayload(child,depth+1);if(found)return found}}return null}
async function imageBlob(data){let d=findImagePayload(data)||data?.data?.[0]||data?.result?.data?.[0]||data?.output?.[0]||data;if(d?.b64_json||d?.b64||d?.partial_image_b64){let raw=d.b64_json||d.b64||d.partial_image_b64,bytes=atob(raw),arr=new Uint8Array(bytes.length);for(let i=0;i<bytes.length;i++)arr[i]=bytes.charCodeAt(i);return new Blob([arr],{type:"image/png"})}let url=d?.url||d?.image_url||data?.image_url||data?.url;if(url){let lastError;for(let attempt=0;attempt<2;attempt++){try{let r=await fetch(url);if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.blob()}catch(e){lastError=e;if(!attempt)await new Promise(resolve=>setTimeout(resolve,800))}}let origin="未知图片域名";try{origin=new URL(url).origin}catch{}throw new Error(`图片已在后台生成，但浏览器无法下载返回图片（${origin}）：${lastError?.message||"连接失败"}。可能是图片域名跨域限制或临时链接失效`)}throw new Error("接口已响应，但没有找到图片数据")}
async function fetchApi(url,options={}){return new Promise((resolve,reject)=>{let xhr=new XMLHttpRequest();xhr.open(options.method||"GET",url,true);xhr.timeout=0;xhr.responseType="blob";for(let[key,value]of Object.entries(options.headers||{}))xhr.setRequestHeader(key,value);xhr.onload=()=>{let headers=new Headers();for(let line of xhr.getAllResponseHeaders().trim().split(/[\r\n]+/)){let i=line.indexOf(":");if(i>0)headers.append(line.slice(0,i).trim(),line.slice(i+1).trim())}resolve(new Response(xhr.response,{status:xhr.status,statusText:xhr.statusText,headers}))};xhr.onerror=()=>reject(new Error("生图连接被远端中断（XHR 状态 0）。客户端已设置为永不超时，请核对中转的跨域长连接配置和扣费记录，不要立即重复提交"));xhr.ontimeout=()=>reject(new Error("生图请求发生超时；当前客户端 timeout=0，正常情况下不会主动超时"));xhr.onabort=()=>reject(new Error("生图请求已被中止"));xhr.send(options.body??null)})}
async function parseApiResponse(res){let type=(res.headers.get("content-type")||"").toLowerCase();if(type.startsWith("image/"))return{directBlob:await res.blob()};if(type.includes("text/event-stream")&&res.body?.getReader){let reader=res.body.getReader(),decoder=new TextDecoder(),buffer="",latest=null,fallback=null,streamError=null,consume=line=>{let text=line.trim();if(!text.startsWith("data:"))return;text=text.replace(/^data:\s*/,"");if(!text||text==="[DONE]")return;try{let parsed=JSON.parse(text);fallback=parsed;let found=findImagePayload(parsed);if(found)latest=found;let message=parsed?.error?.message||((parsed?.type||"").includes("error")?parsed?.message:"");if(message)streamError=new Error(message)}catch{}};try{while(true){let{value,done}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done});let lines=buffer.split(/\r?\n/);buffer=lines.pop()||"";lines.forEach(consume);if(done)break}if(buffer.trim())consume(buffer)}catch(e){if(latest)return latest;throw new Error(`图片流接收中断：${e?.message||"网络连接失败"}`)}if(latest)return latest;if(streamError)throw streamError;if(fallback)return fallback;throw new Error(`接口流式响应结束，但没有收到图片数据（HTTP ${res.status}）`)}let raw=await res.text(),text=raw.trim();if(!text)throw new Error(`接口返回空内容（HTTP ${res.status}）`);try{return JSON.parse(text)}catch{}let events=text.split(/\r?\n/).filter(x=>x.trim().startsWith("data:")).map(x=>x.replace(/^\s*data:\s*/,"")).filter(x=>x&&x!=="[DONE]"),fallback=null;for(let i=events.length-1;i>=0;i--){try{let parsed=JSON.parse(events[i]);fallback||=parsed;if(findImagePayload(parsed))return parsed}catch{}}if(fallback)return fallback;if(/^https?:\/\//i.test(text))return{url:text};if(/^data:image\//i.test(text)){let comma=text.indexOf(",");return{b64:text.slice(comma+1)}}throw new Error(`接口返回格式暂不兼容（HTTP ${res.status}，类型 ${type||"未知"}）`)}
const LINE_ART_PROMPT="请根据原图生成简化的动漫风格黑白线稿，不是完整照搬，而是进行干净清晰的线稿化重绘。保留原图的整体构图、主体位置、人物动态、主要物体外形和基本识别特征，保持原图比例。只保留大轮廓、关键结构和必要内部线条，主动省略花纹、纹理、装饰线和不必要小细节，整体简洁清爽，留白充足，适合儿童涂色、SVG转换或绘图仪输出。人物只保留外轮廓、五官、发型、主要发饰、大块服装结构和少量褶皱线。场景和物体只保留主要外轮廓、基本结构和少量内部线条。如有文字：保留的文字改为镂空描边线稿字；删除的文字只删除字形本身，注意只删除小字，不能删除大标题，不删除文字底框、标题牌、文本框、分隔线、卷轴结构和原有版式，框内留白。线条要求纯黑色线条、纯白色背景、无灰度、无阴影、无颜色、无渐变、无杂线、无脏边。全图不得出现任何实心黑色填充，所有封闭区域内部保持白色。";
function lineArtRequestSize(sourceDimensions) {
  const aspect = sourceDimensions.width / sourceDimensions.height;
  let longSide=3360,width,height,minPixels=655360,maxPixels=8294400;
  if(aspect>=1){width=longSide;height=Math.max(16,Math.round(longSide/aspect/16)*16)}else{height=longSide;width=Math.max(16,Math.round(longSide*aspect/16)*16)}
  let pixels=width*height;if(pixels>maxPixels){let scale=Math.sqrt(maxPixels/pixels);width=Math.max(16,Math.floor(width*scale/16)*16);height=Math.max(16,Math.floor(height*scale/16)*16)}
  pixels=width*height;if(pixels<minPixels){let scale=Math.sqrt(minPixels/pixels);width=Math.ceil(width*scale/16)*16;height=Math.ceil(height*scale/16)*16}
  while(width*height>maxPixels){if(width>=height)width-=16;else height-=16}
  return{width,height,size:`${width}x${height}`}
}
