// Preserved style rules, request formats, and account configuration.
const $=id=>document.getElementById(id), els={age:$("age"),person:$("person"),titleMode:$("titleMode"),smallText:$("smallText"),textBoxes:$("textBoxes"),size:$("size"),titleText:$("titleText"),titleField:$("titleField"),subject:$("subject"),referenceInput:$("referenceInput"),referenceList:$("referenceList"),referenceCount:$("referenceCount"),generate:$("generate"),gallery:$("gallery"),modal:$("modal"),toast:$("toast")};
const SETTINGS_KEY="tonghua-commercial-settings-v1",PARAM_KEY="tonghua-commercial-params-v1",LOG_KEY="tonghua-commercial-logs-v1",THEME_HISTORY_KEY="tonghua-commercial-theme-history-v1",DB_NAME="tonghua-commercial-images-v1",STORE="images",MAX_IMAGES=50,REFERENCE_GALLERY_KEY="tonghua-commercial-reference-gallery-v1",MAX_REFERENCE_IMAGES=10;

let contextItem=null, activeJobs=0, imageEditDrafts=new Map(), imageEditCurrentItem=null, quotaPromise=null;
let uploadedReferences=[], galleryReferenceItems=new Map();
let galleryReferenceIds=new Set();
try { const ids=JSON.parse(localStorage.getItem(REFERENCE_GALLERY_KEY)||"[]"); if(Array.isArray(ids))galleryReferenceIds=new Set(ids.map(String)); } catch {}
// 基础隐藏：运行时组合，界面、历史与本地存储均不会保存完整风格词。
const hidden=["。晰清缘边素元面画持保须必面画但，滑平械机度过般图量矢脑电免避，迹痕色叠量少和触笔克马微轻有见可，亮明艳鲜度和饱高色颜，明分块色，色上涂平笔克马用础基稿线在。感计设平扁量矢要不，风纸贴要不，风画插廓轮无要不，感涂厚要不，感彩水要不。迹痕绘手显明有，滑平械机不，化变细粗和动抖然自有条线。线节细部内与线廓轮色黑显明晰清有都体主有所和字文、物人，稿起笔线勾色黑用先须必。色配亮明艳鲜度和饱高，格风画题主童儿，风绘手笔克马漫动","。感次层景背的体主裹包成形色浅和蓝浅用可，空天与面地实真化弱可。乱杂不但富丰面画让，砌堆铺平免避，富丰次层，系关压叠和挡遮、插穿后前有间之素元体主。素元小碎细散零用使不，缀点行进素元关相型造大量少用使，出突体主，满饱凑紧面画。型造准标化业工要不，晰清构结但歪略廓轮，张夸当适以可例比部局，形变然自和称对不微轻留保，爱可型造","。质气画插漫动童儿有具，动生光阳情表，象形物人国中是须必，现出物人有果如"].map(s=>[...s].reverse().join(""));
const ageRules={grade1_2:[..."节细杂复少减，艳鲜彩色，晰清体主，爱可单简型造，小身大头物人，张夸例比版Q，格风画绘童儿龄低"].reverse().join(""),grade3_6:[..."感计设定一有具，楚清次层间空，中适节细，整完构结，化龄幼度过不但爱可版Q，风画插漫动童儿"].reverse().join(""),junior:[..."力现表术艺有具，富丰节细，感计设有图构，理合系关间空，熟成加更型造，然自例比，风画插年少"].reverse().join("")};
const titleRules={round:[..."。确精式稿计设和称对整规度过、条线匀过直过、感质印打、感量矢、体字刷印要不，强感写手，爱可草潦，形变张夸，满饱实厚画笔。字文挡遮要不素元面画，素元面画挡遮能字文意注，系关挡遮然自成形素元面画与并，大太要不字题标，字术艺写手笔克马体粗用使题标"].reverse().join(""),hard:[..."。体字量矢脑电、体字刷印准标、体字通卡润圆要不，感则规不微轻和迹痕绘手然自有具，充填涂平色颜度和饱高用使部内，边描粗色黑晰清有廓轮外，感角尖和折方有，显明处折转，力有满饱，实厚壮粗体字。字文挡遮要不素元面画，素元面画挡遮能字文意注，系关挡遮然自成形素元面画与并，大太要不字题标，格风字术艺绘手画题主童儿用采字文题标"].reverse().join("")};
function params(){return{age:els.age.value,person:els.person.value,titleMode:els.titleMode.value,smallText:els.smallText.value,textBoxes:els.textBoxes.value,size:els.size.value,quality:"high",titleText:els.titleText.value.trim(),subject:els.subject.value.trim()}}
function buildPrompt(p,hasReferences=false){let a=[`主体：${p.subject}。`,ageRules[p.age],hidden.join("\n")];a.push(p.person==="with"?"画面中必须出现中国人物形象，表情阳光生动。":"画面中不能出现人物。");if(p.titleMode!=="none")a.push(`标题文字：${p.titleText||"根据主题自动生成简短中文标题"}。${titleRules[p.titleMode]}`);else a.push("画面不要标题。");if(p.smallText==="none")a.push("除了指定标题外，不要出现任何中文、英文、拼音、数字、小字、标志、水印或乱码。");if(+p.textBoxes)a.push(`画面中包含${p.textBoxes}个留白清晰、与构图融合的文本框。`);a.push(p.size==="1.4:1"?"画布必须采用标准A4横版比例进行构图，重要内容完整保留在画布安全区域内。":"画布必须采用标准A4竖版比例进行构图，重要内容完整保留在画布安全区域内。");a.push("整体氛围明亮、童趣、生动，主体突出，画面完整。");if(hasReferences)a.push("引用参考图中的元素进行设计。");return a.join("\n")}
function getSettings(){let saved={};try{saved=JSON.parse(localStorage.getItem(SETTINGS_KEY)||"{}")||{}}catch{}return{apiBase:"https://vip.aittco.com/v1",apiPath:"/images/generations",taskApiBase:location.protocol==="file:"?"":location.origin+"/api/image-tasks",model:"gpt-image-2",points:3,apiKey:typeof saved.apiKey==="string"?saved.apiKey:""}}
function quotaPoints(value){let n=Number(value);return Number.isFinite(n)?n/50000:null}function formatPoints(value){if(value==null)return"--";return new Intl.NumberFormat("zh-CN",{maximumFractionDigits:2}).format(value)+" 积分"}function setQuotaState(state,data,message){let badge=$("connectionBadge"),dotClass=state==="ready"?"ready":state==="low"?"low":state==="error"?"error":"";badge.classList.toggle("quota-low",state==="low");badge.classList.toggle("quota-error",state==="error");if(state==="loading")badge.innerHTML='<i class="status-dot"></i>正在查询额度';else if(state==="empty")badge.innerHTML='<i class="status-dot"></i>密钥待设置';else if(state==="error")badge.innerHTML='<i class="status-dot error"></i>密钥不可用';else{let remaining=data?.unlimited_quota?"无限额度":formatPoints(quotaPoints(data?.total_available));badge.innerHTML=`<i class="status-dot ${dotClass}"></i>剩余 ${remaining}`}$('quotaRemaining').textContent=data?(data.unlimited_quota?"无限额度":formatPoints(quotaPoints(data.total_available))):"--";$('quotaUsed').textContent=data?formatPoints(quotaPoints(data.total_used)):"--";let expires=Number(data?.expires_at||0);$('quotaExpiry').textContent=data?(expires>0?new Date(expires*1000).toLocaleDateString("zh-CN"):"永不过期"):"--";$('quotaMessage').textContent=message||"保存密钥后即可查询，不会消耗积分。"}
async function refreshQuota({silent=false}={}){let s=getSettings();if(!s.apiKey){setQuotaState("empty",null);return null}if(quotaPromise)return quotaPromise;setQuotaState("loading",null,"正在向中转查询密钥额度……");let button=$("refreshQuota");button.disabled=true;quotaPromise=(async()=>{try{let origin=new URL(s.apiBase).origin,res=await fetch(origin+"/api/usage/token/",{method:"GET",headers:{Authorization:`Bearer ${s.apiKey}`},cache:"no-store"}),payload=await res.json().catch(()=>({})),data=payload?.data;if(!res.ok||!data)throw new Error(payload?.message||`额度查询失败（HTTP ${res.status}）`);let remaining=quotaPoints(data.total_available),state=!data.unlimited_quota&&remaining!=null&&remaining<3?"low":"ready",modelOk=!data.model_limits_enabled||data.model_limits?.[s.model]===true,msg=modelOk?`密钥“${data.name||"未命名"}”验证成功；额度来自中转实时数据。`:`密钥有效，但当前密钥的模型限制中没有 ${s.model}。`;setQuotaState(state,data,msg);if(state==="low"&&!silent)toast("剩余积分不足一次生图，请及时充值");return data}catch(e){setQuotaState("error",null,e?.message||"额度查询失败");if(!silent)toast(e?.message||"额度查询失败");return null}finally{button.disabled=false;quotaPromise=null}})();return quotaPromise}

function themeHistory(){try{let a=JSON.parse(localStorage.getItem(THEME_HISTORY_KEY)||"[]");return Array.isArray(a)?a:[]}catch{return[]}}function rememberTheme(p){let a=themeHistory().filter(x=>x.subject!==p.subject);a.unshift({subject:p.subject,state:{...p},time:new Date().toLocaleString("zh-CN",{month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"})});localStorage.setItem(THEME_HISTORY_KEY,JSON.stringify(a.slice(0,50)));renderThemeHistory()}function applyThemeRecord(record){Object.keys(record.state||{}).forEach(k=>{if(els[k]&&record.state[k]!=null)els[k].value=record.state[k]});els.subject.value=record.subject||"";updateForm();document.querySelector(".sidebar").scrollTo({top:0,behavior:"smooth"});els.subject.focus();toast("已应用历史主题和参数")}function renderThemeHistory(){let a=themeHistory(),box=$("recentThemeList");box.innerHTML=a.length?a.map((x,i)=>`<button class="recent-item" type="button" data-theme-index="${i}" title="${escapeHTML(x.subject)}"><b>${escapeHTML(x.subject)}</b><small>${escapeHTML(x.time)}</small></button>`).join(""):'<p class="recent-empty">提交生成后，主题记录会显示在这里。</p>'}
function renderLogs(){let a=logs();$("logSummary").textContent=a.length?`共 ${a.length} 条记录 · 成功 ${a.filter(x=>x.success).length} 条`:"暂无生成记录";$("logBody").innerHTML=a.length?a.map(x=>{let reason=x.success?"—":x.error||"旧记录未保存具体原因";return `<tr><td>${escapeHTML(x.time)}</td><td title="${escapeHTML(x.subject)}">${escapeHTML(x.subject.slice(0,22))}</td><td>${escapeHTML(x.size)} / ${escapeHTML(x.quality)}</td><td>${x.points}</td><td class="${x.success?"success":"failed"}">${x.success?"成功":"失败"}</td><td class="failure-reason ${x.success?"":"has-error"}" title="${escapeHTML(reason)}">${escapeHTML(reason)}</td></tr>`}).join(""):'<tr><td colspan="6" style="text-align:center;color:#7b8984">暂无记录</td></tr>'}
function escapeHTML(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}

let taskAudioContext=null;function unlockTaskAudio(){if(taskAudioContext)return taskAudioContext;let AudioEngine=window.AudioContext||window.webkitAudioContext;if(!AudioEngine)return null;try{taskAudioContext=new AudioEngine();let oscillator=taskAudioContext.createOscillator(),gain=taskAudioContext.createGain();gain.gain.value=0;oscillator.connect(gain);gain.connect(taskAudioContext.destination);oscillator.start();oscillator.stop(taskAudioContext.currentTime+.01)}catch{}return taskAudioContext}function scheduleTaskTone(success){let context=unlockTaskAudio();if(!context)return;let now=context.currentTime+.02,notes=success?[[659,.11],[880,.2]]:[[220,.17],[165,.28]];notes.forEach((note,index)=>{let oscillator=context.createOscillator(),gain=context.createGain(),start=now+index*.12,end=start+note[1];oscillator.type=success?"sine":"triangle";oscillator.frequency.setValueAtTime(note[0],start);gain.gain.setValueAtTime(.0001,start);gain.gain.exponentialRampToValueAtTime(success?.065:.075,start+.018);gain.gain.exponentialRampToValueAtTime(.0001,end);oscillator.connect(gain);gain.connect(context.destination);oscillator.start(start);oscillator.stop(end+.02)})}function playTaskSound(success){let context=unlockTaskAudio();if(!context)return;if(context.state==="suspended")context.resume().then(()=>scheduleTaskTone(success)).catch(()=>{});else scheduleTaskTone(success)}
function showHelp(target){let bubble=$("helpBubble"),r=target.getBoundingClientRect();bubble.textContent=target.dataset.tip||"";bubble.classList.add("open");bubble.style.visibility="hidden";bubble.style.left="0px";bubble.style.top="0px";let w=bubble.offsetWidth,h=bubble.offsetHeight,left=r.right+8,top=r.top-h-8;if(left+w>innerWidth-8)left=innerWidth-w-8;if(top<8)top=r.bottom+8;bubble.style.left=Math.max(8,left)+"px";bubble.style.top=Math.max(8,Math.min(top,innerHeight-h-8))+"px";bubble.style.visibility="visible"}function hideHelp(){$("helpBubble").classList.remove("open")}
